name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish -c Release
      
    - name: Yandex registry login
      run: docker login --username oauth --password ${{ secrets.YANDEX_REGISTRY_OAUTH_TOKEN }} cr.yandex
    - name: Calculate docker tag
      run: echo "IMAGE_TAG=$(date -u +%Y%m%d).$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    - name: Docker build
      run: docker build -t "cr.yandex/crp7bmi62lh3k77mpdei/yandex-time:${{ env.IMAGE_TAG }}" .
    - name: Docker push
      run: docker push "cr.yandex/crp7bmi62lh3k77mpdei/yandex-time:${{ env.IMAGE_TAG }}"
      
    - name: Install Yandex Cloud CLI
      run: curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
    - name: Trigger container update
      run: ~/yandex-cloud/bin/yc compute instance update-container ef3m6cd076n1ov6u42nf --container-image "cr.yandex/crp7bmi62lh3k77mpdei/yandex-time:${{ env.IMAGE_TAG }}" --token ${{ secrets.YANDEX_REGISTRY_OAUTH_TOKEN }}
